<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Ecbank * @package    Ecbank_EcbankWebatm * @copyright  Copyright (c) 2010 Ecbank (http://www.ecbank.com.tw)
 */
?>

<?php $paymentInfo = $this->_getOrder()->getPayment()->getMethodInstance()->setParams(); ?>
<form method="post" id ="ecpay_checkout" action="https://ecpay.com.tw/form_Sc_to5.php">
<input type="hidden" name="act" value="<?php echo 'auth';?>">
<input type="hidden" name="client" value="<?php echo $paymentInfo['client'];?>">
<input type="hidden" name="amount" value="<?php echo $paymentInfo['amount'];?>">
<input type="hidden" name="od_sob" value="<?php echo $paymentInfo['od_sob'];?>">
<input type="hidden" name="roturl" value="<?php echo $paymentInfo['roturl'];?>">
<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('ecpay_checkout');
    window.onload = paymentform.submit();
//]]>
</script>