<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Ecbank * @package    Ecbank_EcbankAlipay * @copyright  Copyright (c) 2010 Ecbank (http://www.ecbank.com.tw)
 */
?>
<?php  echo $this->sendGoodsInfo();  ?>
<form name="ecbankalipay_checkout" id="ecbankalipay_checkout" action="<?php echo $this->getFormAction();?>" method="POST">
<?php if (is_array($this->getFormData())): ?>
    <?php foreach ($this->getFormData() as $name => $value): ?>
    
        <?php if(is_array($value)): ?>
            <?php foreach($value as $n => $v): ?>
                <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $v; ?>"/>
            <?php endforeach; ?>
        <?php else :  ?>
            <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>"/>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
</form>

<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('ecbankalipay_checkout');
    window.onload = paymentform.submit();
//]]>
</script>