<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Ecbank * @package    Ecbank_EcbankWebatm * @copyright  Copyright (c) 2010 Ecbank (http://www.ecbank.com.tw)
 */
?>

<?php $paymentInfo = $this->_getOrder()->getPayment()->getMethodInstance()->sendParams(); ?>
<?php 	
	$returnUrl = Mage::getUrl('customer/account');
	if(!isset($paymentInfo['error']) || $paymentInfo['error'] != '0')
	{        
		$def_url= '取號錯誤('.$paymentInfo['error'].')';
    }
	else{
		$def_url.='<font size=6>繳費資訊:</font><br>';
		$def_url.='<font size=+1>轉帳銀行代碼:(<font color=blue size=+2>'.$paymentInfo['bankcode'].'</font>)';
		$def_url.='轉帳銀行帳戶:(<font color=blue size=+2>'.$paymentInfo['vaccno'].'</font>)';
		$def_url.="<br>持玉山銀行金融卡轉帳可免付跨行交易手續費，其它銀行依該行跨行手續費規定扣繳<br><a href=https://netbank.esunbank.com.tw/webatm/> 玉山銀行 WEB-ATM https://netbank.esunbank.com.tw/webatm/</a>";
		$def_url.='<br><br><center><a href ='.$returnUrl.'>按此返回訂單列表</a></center></font>';
	}
	echo $def_url;?>

<script type="text/javascript">
//<![CDATA[
    //var paymentform = document.getElementById('ecbankcvs_checkout');
    //window.onload = paymentform.submit();
//]]>
</script>