<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Ecbank * @package    Ecbank_EcbankWebatm * @copyright  Copyright (c) 2010 Ecbank (http://www.ecbank.com.tw)
 */
?>

<?php $paymentInfo = $this->_getOrder()->getPayment()->getMethodInstance()->sendParams(); ?>
<?php 	$returnUrl = Mage::getUrl('customer/account');	
if(!isset($paymentInfo['error']) || $paymentInfo['error'] != '0')		    
	$def_url = '取條碼錯誤('.$paymentInfo['error'].')';		
else {		    
	$def_url = '<font size=+1>條碼訂單編號: '.$paymentInfo['od_sob'].'<br>';			
	$lineurl = 'https://ecbank.com.tw/order/barcode_print.php?mer_id='.$paymentInfo['mer_id'].'&tsr='.$paymentInfo['tsr'].'';					    $def_url.= '請列印超商條碼帳單至超商繳費 [<a href='.$lineurl.' target=_blank>點此列印</a>]';
	$def_url.= '<br><br><center><a href ='.$returnUrl.'>按此返回訂單列表</a></center></font>';
	}	
	echo $def_url;?>

<script type="text/javascript">
//<![CDATA[
    //var paymentform = document.getElementById('ecbankcvs_checkout');
    //window.onload = paymentform.submit();
//]]>
</script>