<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Ecbank
 * @package    Ecbank_EcbankWebatm
 * @copyright  Copyright (c) 2010 Ecbank (http://www.ecbank.com.tw)
 */
?>
<html>

<body>

<div class="page-head">
	<?php echo print_r($_RQUEST,true);  ?><br>
	
    <h3><?php echo Mage::helper('ecbankwebatm')->__('ERROR') ?></h3>
	

</div>
<p><?php echo Mage::helper('ecbankwebatm')->__(' <a href="%s">return ecbank</a>.', $this->getContinueShoppingUrl()) ?></p>
<?php exit;?>
</body>
</html>
